image: typo3gmbh/php80

stages:
  - code_quality

code_quality:
  stage: code_quality
  script:
    - composer config --auth gitlab-token.gitlab.com "$GITLAB_TOKEN" --no-ansi --no-interaction
    - composer install --no-progress --no-ansi --no-interaction --optimize-autoloader
    - composer exec svenpet-typo3-coding-standards extension
    - composer ci:lint:debugoutput
    - composer ci:test:php
    - composer ci:lint:typoscript
