image: webdevops/php-dev:8.0

stages:
  - code_quality
  - deployment

code_quality:
  stage: code_quality
  script:
    - composer config --auth gitlab-token.gitlab.com "$GITLAB_TOKEN" --no-ansi --no-interaction
    - composer install --no-progress --no-ansi --no-interaction --optimize-autoloader
    - curl -sL https://deb.nodesource.com/setup_14.x | bash
    - apt-get install nodejs
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt update -y && apt install yarn -y
    - yarn install --ignore-engines
    - composer exec svenpet-typo3-coding-standards project
    - composer ci:lint:debugoutput
    - composer ci:test:php
    - composer ci:lint:typoscript
    - yarn ci:lint:stylelint
    - yarn ci:lint:eslint

build_prod_assets:
  stage: build_prod_assets
  script:
    - composer install --no-dev --no-cache --no-progress --no-ansi --no-interaction --optimize-autoloader
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt update -y && apt install yarn -y
    - yarn install --ignore-engines
    - yarn encore prod
  artifacts:
    name: artifacts
    paths:
      - ./public/build
    expire_in: '2h'
  only:
    - master

deploy_to_production:
  stage: deployment
  image: alpine
  before_script:
    - apk add openssh-client
    - apk add rsync openssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - rsync -avzP --delete -e "ssh -o StrictHostKeyChecking=no" ./public/build/* "$P_NUMBER"@"$P_NUMBER".webspaceconfig.de:~/html/"$REL_PATH_TO_INSTALLATION"/public/build
    - ssh -o StrictHostKeyChecking=no "$P_NUMBER"@"$P_NUMBER".mittwaldserver.info "cd html/"$REL_PATH_TO_INSTALLATION"/ && git reset --hard && git pull && composer install --no-dev && ./vendor/bin/typo3cms database:updateschema && ./vendor/bin/typo3cms cache:flush"
  only:
    - master
  environment:
    name: production
    url: "$URL_TO_WEBSITE"
